apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gd2wbeto9-nodejs
  janus-idp.io/tekton: gd2wbeto9-nodejs
  backstage.io/kubernetes-id: gd2wbeto9-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gd2wbeto9-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
